# Eager Execution basics

- This is an introductory tutorial for using TensorFlow. It will cover:
    
    - Importing requried packages
    
    - Creating an using Tensors
    
    - Using GPU acceleration
    
    - Datasets

## Import TensorFlow

- To get started, import the `tensorflow` module and enable eager execution. Eager execution enables a more interactive frontend to TensorFlow, the details of which we will discuss much later.

In [1]:
import tensorflow as tf

tf.enable_eager_execution()

## Tensors

- A Tensor is a multi-dimensional array. Similar to NumPy `ndarray` objects, `Tensor` objects have a data type and a shape. Additionally, Tensors can reside in accelerator (like GPU) memory. TensorFlow offers a rich library of operations (`tf.add`, `tf.matmul`, `tf.linalg.inv`, etc.) that consume and produce Tensors. These operations automatically convert native Python types. For example:

In [2]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64("hello world"))

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


- Each Tensor has a shape and a datatype

In [3]:
x = tf.matmul([[1]], [[2,3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


- The most obvious differences between NumPy arrays and TensorFlow Tensors are:

    1. Tensors can be backed by accelerator memory (like GPU, TPU).
    
    2. Tensors are immutable.

### NumPy Compatibility

- Conversion between TensorFlow Tensors and NumPy ndarrays is quite simple as:

    - TensorFlow operations automatically convert NumPy ndarrays to Tensors.
    
    - NumPy operations automatically convert Tensors to NumPy ndarrays.
    
- Tensors can be explicitly converted to NumPy ndarrays by invoking the `.numpy()` method on them. These conversions are typically cheap as the array and Tensor share the underlying memory representation if possible. However, sharing the underlying representation isn't always possible since the Tensor may be hosted in GPU memory while NumPy arrays are always backed by host memory, and the conversion will thus involve a copy from GPU to host memory.

In [4]:
import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


## GPU acceleration

- Many TensorFlow operations can be accelerated by using the GPU for computation. Without any annotations, TensorFlow automatically decides whether to use the GPU or CPU for an operation (and copies the tensor between CPU and GPU memory if necessary). Tensors produced by an operation are typically backed by the memory of the device on which the operation executed. For example:

In [5]:
x = tf.random_uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0: "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
True
Is the Tensor on GPU #0: 
True


### Device Names

- The `Tensor.device` property provides a fully qualified string name of the device hosting the contents of the tensor. This name encodes many details, such as an identifier of the network address of the host on which this program is executing and the device within that host. This is required for distributed execution of a TensorFlow program. This string ends with `GPU:<N>` if the tensor is placed on the `N`-th GPU on the host.

### Explicit Device Placement

- The term "placement" in TensorFlow refers to how individual operations are assigned (placed on) a device for execution. As mentioned above, when there is no explicit guidance provided, TensorFlow automatically decides which device to execute an operation, and copies Tensors to that device if needed. However, TensorFlow operations can be explicitly placed on specific devices using the `tf.device` context manager. For example:

In [6]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(1000):
        tf.matmul(x, x)
        
    result = time.time() - start
    
    print("1000 loops: {:0.2f}ms".format(1000*result))
    
# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)
    
# Force execution on GPU #0 if available
if tf.test.is_gpu_available():
    print("On GPU:")
    with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd, etc.
        x = tf.random_uniform([1000, 1000])
        assert x.device.endswith("GPU:0")
        time_matmul(x)

On CPU:
1000 loops: 17870.92ms
On GPU:
1000 loops: 426.80ms


## Datasets

- This section demonstrates the use of the `tf.data.Dataset` API to build pipelines to feed data to your model. It covers:

    - Creating a `Dataset`.
    
    - Iteration over a `Dataset` with eager execution enabled.
    
- We recommed using the `Dataset`s API for building performant, complex input pipelines from simple, re-usable pieces that will feed your model's training or evaluation loops.

- If you're familiar with TensorFlow graphs, the API for constructing the `Dataset` object remains exactly the when eager execution is enabled, but the process of iterating over elements of the dataset is slightly simpler. You can use Python iteration over the `tf.data.Dataset` object and do not need to explicitly create and `tf.data.Iterator` object. As the result, the discussion on iterators in the [TensorFlow Guide](https://www.tensorflow.org/guide/datasets) is not relevant when eager execution is enabled.

### Create a source Dataset

- Create a *source* dataset using one of the factory function like [`Dataset.from_tensors`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensors), [`Dataset.from_tensor_slices`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices) or using objects that read from files like [`TextLineDataset`](https://www.tensorflow.org/api_docs/python/tf/data/TextLineDataset) or [`TFRecordDataset`](https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset). See the [TensorFlow Guide](https://www.tensorflow.org/guide/datasets#reading_input_data) for more information.

In [7]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
Line 2
Line 3
""")
    
    ds_file = tf.data.TextLineDataset(filename)

In [8]:
filename

'C:\\Users\\SHIOKO\\AppData\\Local\\Temp\\tmp7j_3l16o'

### Apply transformations

- Use the transformations functions like [`map`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map), [`batch`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#batch), [`shuffle`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shuffle), etc. to apply transformations to the records of the dataset. Set the [API documentation for `tf.data.Dataset`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) for details.

In [9]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

### Iterate

- Whe eager execution is enabled `Dataset` objects support iteration. If you're familliar with the use of `Dataset`s in TensorFlow graphs, note taht there is no need for calls to `Dataset.make_one_shot_iterator()` or `get_next()` calls.

In [11]:
print('Elements of ds_tensors:')
for x in ds_tensors:
    print(x)
    
print('\nElements in ds_file:')
for x in ds_file:
    print(x)

Elements of ds_tensors:
Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([ 9 25], shape=(2,), dtype=int32)
tf.Tensor([36 16], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3'], shape=(1,), dtype=string)
